/*
 * This source file was generated by the Gradle 'init' task
 */
package com.jdisc.toolchain

import org.gradle.testfixtures.ProjectBuilder
import spock.lang.Specification

/**
 * A simple unit test for the 'com.jdisc.toolchain.github-organization-repo-mirror' plugin.
 */
class GithubOrganizationRepositoriesMirrorPluginTest extends Specification {
    def "plugin registers task"() {
        given:
        def project = ProjectBuilder.builder().build()

        when:
        project.plugins.apply("com.jdisc.toolchain.github-organization-repo-mirror")

        then:
        project.tasks.findByName("cloneMirrorRepos") != null
    }
}
